# vim: et ts=2 sts=2 sw=2

language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - android-24
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - gradle wrapper -b wrapper.gradle
  - cp travis.gradle.properties gradle.properties

script:
  - set -e
  - ./gradlew check jacocoTestReport
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success: bash <(curl -s https://codecov.io/bash)
