# vim: et ts=2 sts=2 sw=2

language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-24
    - android-23
    - android-22
    - extra-android-m2repository

before_script:
  - gradle wrapper -b wrapper.gradle
  - cp travis.gradle.properties gradle.properties

script: ./gradlew check
